import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-gpu']});
const context=await browser.newContext({viewport:{width:1280,height:980}});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
let latest;
page.on('websocket',ws=>ws.on('framereceived',({payload})=>{try{const m=JSON.parse(payload);if(m.type==='state')latest=m}catch{}}));
const until=async(fn)=>{for(let i=0;i<150;i++){if(fn())return;await page.waitForTimeout(15)}throw Error('Browser condition timed out')};
await page.goto('http://localhost:8787');await page.getByRole('button',{name:'进入单人练习场'}).waitFor();
await page.waitForTimeout(400);
await page.screenshot({path:path.join(root,'home-preview.png'),fullPage:true});
await page.getByRole('button',{name:'进入单人练习场'}).click();
await page.waitForTimeout(3300);
await page.screenshot({path:path.join(root,'game-preview.png'),fullPage:true});
await page.getByRole('button',{name:'穿泡练习',exact:true}).click();
await page.locator('#game').focus();await page.keyboard.down('ArrowUp');
await until(()=>latest?.players[0]?.activation&&latest.time-latest.players[0].activation.since>=.58);
await page.keyboard.press('Space');await page.waitForTimeout(310);await page.keyboard.up('ArrowUp');
assert.equal(latest.players[0].phaseCount,1);assert(latest.players[0].y<6);
await page.getByRole('checkbox',{name:'显示格线和判定位置'}).check();
await page.screenshot({path:path.join(root,'practice-preview.png'),fullPage:true});
await page.getByRole('button',{name:'声音：开'}).click();assert.equal(await page.getByRole('button',{name:'声音：关'}).count(),1);
await page.getByRole('button',{name:'玩法说明'}).click();assert(await page.locator('#help-dialog').isVisible());
await page.getByRole('button',{name:'关闭说明'}).click();
await page.getByRole('button',{name:'借泡上墙',exact:true}).click();await page.locator('#game').focus();await page.keyboard.down('ArrowUp');
await until(()=>latest?.players[0]?.activation&&latest.time-latest.players[0].activation.since>=.58);
await page.keyboard.press('Space');await page.waitForTimeout(140);await page.keyboard.up('ArrowUp');
await until(()=>latest.players[0].onWall==='6,6');
await page.screenshot({path:path.join(root,'wall-preview.png'),fullPage:true});
await page.getByRole('button',{name:'转向上墙',exact:true}).click();await page.locator('#game').focus();await page.keyboard.down('ArrowRight');
await until(()=>latest?.players[0]?.activation&&latest.time-latest.players[0].activation.since>=.58);
await page.keyboard.press('Space');await page.keyboard.down('ArrowUp');await page.waitForTimeout(125);await page.keyboard.up('ArrowUp');await page.keyboard.up('ArrowRight');
await until(()=>latest.players[0].onWall==='7,6');
await page.screenshot({path:path.join(root,'wall3-preview.png'),fullPage:true});
await page.getByRole('button',{name:'走穿练习',exact:true}).click();await page.locator('#game').focus();await page.keyboard.down('ArrowUp');
await until(()=>latest?.drill==='run'&&latest?.players[0]?.activation&&latest.time-latest.players[0].activation.since>=.56);
await page.keyboard.press('Space');await page.waitForTimeout(450);await page.keyboard.up('ArrowUp');assert(latest.players[0].phaseCount>=1);assert(latest.players[0].y<6);
await page.getByRole('button',{name:'借泡上柱',exact:true}).click();await page.locator('#game').focus();await page.keyboard.down('ArrowUp');
await until(()=>latest?.drill==='pillar'&&latest?.players[0]?.activation&&latest.time-latest.players[0].activation.since>=.56);
await page.keyboard.press('Space');await page.waitForTimeout(160);await page.keyboard.up('ArrowUp');await until(()=>latest.players[0].onWall==='6,6');
await page.screenshot({path:path.join(root,'pillar-preview.png'),fullPage:true});
await page.getByRole('button',{name:'包子房练习',exact:true}).click();await page.locator('#game').focus();await page.keyboard.down('ArrowUp');await page.waitForTimeout(350);await page.keyboard.up('ArrowUp');
await until(()=>latest?.drill==='house'&&latest.players[0].inHouse===0);await page.screenshot({path:path.join(root,'house-preview.png'),fullPage:true});
await page.getByRole('button',{name:'离开',exact:true}).click();
await page.locator('#nickname').fill('红队测试');await page.getByRole('button',{name:'创建联机房间'}).click();
await page.locator('#room-panel').waitFor({state:'visible'});const code=await page.locator('#room-number').textContent();
const second=await context.newPage();second.on('pageerror',e=>errors.push(e.message));await second.goto('http://localhost:8787');
await second.locator('#nickname').fill('蓝队测试');await second.getByRole('button',{name:`加入房间 ${code}`,exact:true}).waitFor();
await second.screenshot({path:path.join(root,'lobby-preview.png'),fullPage:true});
await second.getByRole('button',{name:`加入房间 ${code}`,exact:true}).click();
await second.locator('#room-panel').waitFor({state:'visible'});await second.locator('#ready-button').click();
await page.waitForTimeout(100);await page.locator('#ready-button').click();await page.waitForTimeout(1500);
await page.screenshot({path:path.join(root,'countdown-preview.png'),fullPage:true});await page.waitForTimeout(1800);
assert.equal(latest.state,'playing');assert.equal(latest.players.length,2);
assert(await second.locator('#leave-game').isVisible());
await page.screenshot({path:path.join(root,'multiplayer-preview.png'),fullPage:true});
assert.deepEqual(errors,[]);console.log('Browser smoke: real keyboard phasing and wall entry verified; two browser pages created/joined/readied/started a match; assets, sound and help passed; no page errors.');
await browser.close();
